### ISSUE TITLE
Installation failed : theme is not exported from ggtern anymore

### ISSUE THREAD

**Issue by statnmap** [jschoeley/tricolore#10]
The very last version of {ggtern} is now in conformity with version 3.3.0 of {ggplot2}: https://bitbucket.org/nicholasehamilton/ggtern/commits/tag/3.3.0  
Hence, some functions like `theme()` are not anymore exported from {ggtern}.  
You can import `theme` and `theme_classic` from {ggplot2} directly in your `BasicKey()` function I guess.

**Comment by jschoeley** [comment]
Thank you. I pushed a new update to CRAN. You can use the current tricolore version from github for now.

**Comment by statnmap** [comment]
By curiosity, did you remove all `caption = ` because it failed to render ?  
I faced this problem, which is why I did not send a PR :smile:

**Comment by jschoeley** [comment]
Yes. I did not have time to track down the issue so I just circumvented it for the moment. Please tell me if you have any idea where this problem is coming from.
