### ISSUE TITLE
Tricolore keys misbehaving

### ISSUE THREAD

**Issue by VictimOfMaths** [jschoeley/tricolore#11]
Since updating to ggplot 3.3.0 and updating to version 1.2.2. of Tricolore I can no longer make the Tricolore keys work properly:

![image](https://user-images.githubusercontent.com/48697887/80408735-99483a00-88bf-11ea-858a-c73c506cfa3a.png)

Typing 'tric_educ$key' brings up the key as normal, but I can't add it to any plots using either annotation_custom() or with {cowplot}

I also don't seem to be able to amend the key as I could previously, e.g.:

![image](https://user-images.githubusercontent.com/48697887/80409169-4ae76b00-88c0-11ea-959f-92530647d26b.png)

Not sure if this is a Tricolore issue or a {ggtern} one (or if I've done something dumb)?

**Comment by jschoeley** [comment]
Hi Colin,

you need to load `library(ggtern)` whenever you want to modify the tricolore key after creation or use it as part of another ggplot. In order to keep the namespace of the user clean, tricolore only loads those functions from ggtern which are necessary to render the default key.

``` r
library(tricolore)
#> Registered S3 methods overwritten by 'ggtern':
#>   method           from   
#>   grid.draw.ggplot ggplot2
#>   plot.ggplot      ggplot2
#>   print.ggplot     ggplot2

# generate tricolore key and color map
tric_educ <- Tricolore(euro_example, p1 = 'ed_0to2',
                       p2 = 'ed_3to4', p3 = 'ed_5to8')
#> Warning: Ignoring unknown aesthetics: z
tric_educ$key
```

![](https://i.imgur.com/aUmeTyC.png)

``` r

# load library ggtern if you want to use
# the tricolore key as part of other ggplots
# or if you want to modify the key
library(ggtern)
#> Loading required package: ggplot2
#> --
#> Remember to cite, run citation(package = 'ggtern') for further info.
#> --
#> 
#> Attaching package: 'ggtern'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     aes, annotate, ggplot, ggplot_build, ggplot_gtable, ggplotGrob,
#>     ggsave, layer_data, theme_bw, theme_classic, theme_dark,
#>     theme_gray, theme_light, theme_linedraw, theme_minimal, theme_void

euro_example$educ_rgb <- tric_educ$rgb
ggplot(euro_example) +
  geom_sf(
    aes(fill = educ_rgb, geometry = geometry), size = 0.1
  ) +
  scale_fill_identity() +
  annotation_custom(
    ggplotGrob(tric_educ$key),
    xmin = 55e5, xmax = 75e5, ymin = 8e5, ymax = 80e5
  )
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/2rDbLQH.png)

``` r

tric_educ$key + scale_T_continuous('test')
#> Scale for 'T' is already present. Adding another scale for 'T', which will
#> replace the existing scale.
```

![](https://i.imgur.com/AbuBRWw.png)

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by VictimOfMaths** [comment]
Hi Jonas,

My apologies, I have been getting various error messages when running generating my own ternary plots and this was my best effort to recreate the same errors using the example code.

If I follow the example (loading {ggtern} version 3.3.0), but make a simple amendment to the key, then I still get an error (albeit a different one):

![image](https://user-images.githubusercontent.com/48697887/80507651-fbac4380-896e-11ea-8ef3-29bb143eb52c.png)

**Comment by jschoeley** [comment]
No apologies needed. After every ggplot2 update there's always a period where new errors crop up in dependent packages.

Regarding the last error in your example: I'm aware of this but don't know how to solve it yet. The workaround is not to use the `caption` argument in the `labs()` function. You can still give a title and subtitle as only the usage of caption throws an error.
