### ISSUE TITLE
Change in triangle scale

### ISSUE THREAD

**Issue by neli12** [jschoeley/tricolore#12]
Hi! Thank you for this package!

I am trying to use it to construct ternary plot for a RGB raster map. However, I cannot find where I set the limits of the scale of the plot. My raster limits if 0 to 1000.

Could you please give me some insigths about this issue?

Thank very much!!

**Comment by jschoeley** [comment]
Hi. Glad you're using the package. I'm not sure if I got your question right. Do you want to label the sides of the ternary plot from 0 to 1000?

**Comment by neli12** [comment]
Yes. I have a raster stack with three layers and the minimum and maximum of my rasters are 0 and 1000. Since my rasters cover a large area, I have almost 3million values. However, your package plot only 30000. It is any solution for that?

Thank you very much!

**Comment by HaoLi2025** [comment]
Hello, the packages in R did not work for the negative values?

**Comment by jschoeley** [comment]
Hi, yes, the package only works for positive data, i.e. proportions / shares / parts of a whole.
