### ISSUE TITLE
how bulid four factors lengend （square）that like as tricolore 

### ISSUE THREAD

**Issue by hhwills** [jschoeley/tricolore#20]

**Comment by jschoeley** [comment]
It sounds like you are looking for a bivariate color scale. These are not implemented in tricolore but you can find them in the `biscale` package. See https://cran.r-project.org/web/packages/biscale/

![image](https://github.com/jschoeley/tricolore/assets/10901917/f1189970-1e22-44dd-af20-56828bccbfd2)
