### ISSUE TITLE
tricolore is not available for R 4.3.3

### ISSUE THREAD

**Issue by JuanGaleano** [jschoeley/tricolore#21]
Hi Jonas, 

I was trying to install tricolore but it seems it's not available for R 4.3.3. 

Are you planning an update? Is there any other way of using the tricolore function?

Thanks in advance.

**Comment by jschoeley** [comment]
Thank you. As of May 15 2024, tricolore is once again available from CRAN (https://cran.r-project.org/web/packages/tricolore/index.html).

Alternatively, the package can be installed directly from github: `devtools::install_github("jschoeley/tricolore")`
