### ISSUE TITLE
reverse order along each axis

### ISSUE THREAD

**Issue by dylanbeaudette** [jschoeley/tricolore#4]
Thanks for the excellent package. Is there any way to reverse the axis orientation so that they increase counter-clockwise?

Like this:
![image](https://user-images.githubusercontent.com/624277/53993804-3f961680-40e5-11e9-8d9d-97cc9801a778.png)

**Comment by jschoeley** [comment]
Thank you. Yes that is easily done.

```r
# Clockwise rotation of tricolore legend labels
library(tricolore)

P <- as.data.frame(prop.table(matrix(runif(3^6), ncol = 3), 1))
tric <- Tricolore(P, 'V1', 'V2', 'V3')
tric$key +
  ggtern::theme_clockwise()
```

The `Tricolore()` function returns a `ggtern` style `ggplot` object which may be further modified by using `ggplot` or `ggtern` layers such as themes.

**Comment by dylanbeaudette** [comment]
Thanks for the suggestion. The `ggtern::theme_clockwise()` call does in fact reverse the axis labels, but not the logic of the plot itself. Check this out:

Default:
![image](https://user-images.githubusercontent.com/624277/54043748-35762580-4182-11e9-809f-a95188135db7.png)

`colors_and_legend$key + ggtern::theme_clockwise()`:
![image](https://user-images.githubusercontent.com/624277/54043779-432bab00-4182-11e9-967b-114efed2766f.png)

I tried this with the small code sample you suggested with the same results: re-orientation of the axis but not data. Ideas?

**Comment by jschoeley** [comment]
You can re-order the data arguments to `Tricolore()` and thereby change the association between components and axes.

```r
# Reorient the data in a ternary diagram
library(ggtern)
library(tricolore)

data("Feldspar")

Tricolore(Feldspar, 'Ab', 'Or', 'An')
Tricolore(Feldspar, 'An', 'Or', 'Ab')
```
