### ISSUE TITLE
package compositions not installing with R version 3.6.1

### ISSUE THREAD

**Issue by Danieldavid521** [jschoeley/tricolore#5]
installed with dependencies, R version 3.6.1, even rolling back my R version to make this work. Will check back in

**Comment by jschoeley** [comment]
Do you have problems installing the R package "compositions" (https://cran.r-project.org/package=compositions)? If so please contact the maintainer of the "compositions" package (K. Gerald van den Boogaart <support at boogaart.de>). "tricolore" is independent of "compositions".

Best,

Jonas
