### ISSUE TITLE
include git repo in DESCRIPTION file

### ISSUE THREAD

**Issue by JosiahParry** [jschoeley/tricolore#7]
I struggled to find the source code as the git repo isn't located in the `DESCRIPTION` file. Including it could help direct future package issues. 

Thanks! :)

**Comment by jschoeley** [comment]
Good idea. Will do with the next update.

**Comment by zr-sunflower** [comment]
hello，I am a beginner in R. I have the raster data with three bands. How to plot this Ternary choropleth maps？Do I need to convert the data format?
Thanks！
