### ISSUE TITLE
Return dataframe of computed ternary composition

### ISSUE THREAD

**Issue by aboutaaron** [jschoeley/tricolore#8]
Hi,

Thanks again for writing this library! I'm using it for a project and ran into an issue associating some data. Any insight would be helpful. Please let me know if this isn't the proper channel to ask this question or if I should direct this somewhere else.

### Setup

In the Getting Started section, you have the following:

```R
P <- as.data.frame(prop.table(matrix(runif(3^6), ncol = 3), 1))

# color-code each composition and return a corresponding color key
colors_and_legend <- Tricolore(P, 'V1', 'V2', 'V3')

# show the key
colors_and_legend$key
```

This then produces this legend:

![Rplot](https://user-images.githubusercontent.com/856628/69188970-8dc03e00-0aeb-11ea-90df-0301d4104116.png) 

I can then assign the vector of colors to our source data because these two values are the same shape:

```R
P$rgb <- colors_and_legend$rgb
head(P)
```

Now `P` has a new `rgb` column that was generated by `Tricolore`:
```
           V1        V2        V3     rgb
1 0.380671333 0.3224709 0.2968577 #727272
2 0.007142204 0.2794686 0.7133892 #A48AC6
3 0.438993033 0.4253089 0.1356980 #6E8E72
4 0.771708672 0.1112922 0.1169991 #CFB000
5 0.313515151 0.2090149 0.4774700 #A37D7D
6 0.154378381 0.2251785 0.6204431 #CB82C5
```

### Question

What I want to know is, **how can I assign the computed values used to generate the legend to my source dataframe?**

For example, `head(colors_and_legend$key$data)` yields:

```
  id vertex   p1   p2   p3     rgb
1  1      1 1.00 0.00 0.00 #CFB000
2  2      1 0.50 0.25 0.25 #AF9B47
3  3      1 0.75 0.00 0.25 #BC8C67
4  4      1 0.25 0.25 0.50 #A37D7D
5  5      1 0.50 0.00 0.50 #CA7FA1
6  6      1 0.00 0.25 0.75 #CB82C5
```

Is there a way to assign these columns to the corresponding rows in the source data? I tried doing a simple join with the `rgb`, but that ends up introducing duplicate values because the assigned colors are associated with multiple vertices, i.e.:

```
           V1        V2        V3     rgb id vertex   p1   p2   p3
1 0.380671333 0.3224709 0.2968577 #727272 10      1 0.50 0.25 0.25
2 0.380671333 0.3224709 0.2968577 #727272 10      2 0.25 0.50 0.25
3 0.380671333 0.3224709 0.2968577 #727272 10      3 0.25 0.25 0.50
4 0.007142204 0.2794686 0.7133892 #A48AC6 12      1 0.25 0.25 0.50
5 0.007142204 0.2794686 0.7133892 #A48AC6 12      2 0.00 0.50 0.50
6 0.007142204 0.2794686 0.7133892 #A48AC6 12      3 0.00 0.25 0.75
```

I ended up trying to deconstruct the chart using [`ggplot_build`](https://stackoverflow.com/a/25381297/868724), but I'm still missing some necessary information needed to compute the join. Furthermore, I feel like there's likely an easier way to solve this.

Is what I'm trying to do possible and/or is there a better way to do this? Thanks!

**Comment by jschoeley** [comment]
Hi,

> Is there a way to assign these columns to the corresponding rows in the source data?

Every observation/row in your data `P` is associated with a single triangle in the ternary legend and is colored the same as the triangle. Each triangle has a unique id and occupies three rows in the triangle data-set `C`, one row for each vertex.

Merging by color key as you did it is one way to link both tables. *If you don't want duplication of your data rows then you can use a list column (see example below).*

Note that the merge by color method will fail when the legend features multiple triangles with identical colors which may happen in some circumstances. I've shown a more robust approach to determining the triangle id for each observation below.

Why do you need to merge the two data sets in the first place?

Best,

Jonas

``` r
library(tricolore)
#> Registered S3 methods overwritten by 'ggtern':
#>   method           from   
#>   +.gg             ggplot2
#>   grid.draw.ggplot ggplot2
#>   plot.ggplot      ggplot2
#>   print.ggplot     ggplot2
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyverse)

# Join by color and nest columns ------------------------------------------

P <- as.data.frame(prop.table(matrix(runif(3^6), ncol = 3), 1))
tric <- Tricolore(P, 'V1', 'V2', 'V3')
#> Warning: Ignoring unknown aesthetics: z
P$rgb <- tric$rgb

joined <- left_join(P, tric$key$data)
#> Joining, by = "rgb"
nested <-
  joined %>%
  group_by(id) %>%
  nest(key = c(id, vertex, p1, p2, p3))
nested
#> # A tibble: 243 x 5
#>       V1    V2     V3 rgb                key
#>    <dbl> <dbl>  <dbl> <chr>   <list<df[,5]>>
#>  1 0.206 0.730 0.0638 #00AFAE        [3 × 5]
#>  2 0.501 0.369 0.130  #899E56        [3 × 5]
#>  3 0.352 0.261 0.387  #727272        [3 × 5]
#>  4 0.516 0.302 0.183  #899E56        [3 × 5]
#>  5 0.415 0.555 0.0300 #37A789        [3 × 5]
#>  6 0.406 0.400 0.194  #6E8E72        [3 × 5]
#>  7 0.304 0.225 0.471  #A37D7D        [3 × 5]
#>  8 0.195 0.356 0.449  #7A86A1        [3 × 5]
#>  9 0.151 0.576 0.273  #4AA0BB        [3 × 5]
#> 10 0.679 0.224 0.0971 #AF9B47        [3 × 5]
#> # … with 233 more rows
nested$key[[1]]
#> # A tibble: 3 x 5
#> # Groups:   id [16]
#>      id vertex    p1    p2    p3
#> * <dbl>  <dbl> <dbl> <dbl> <dbl>
#> 1    14      1  0     0.75  0.25
#> 2    14      2  0.25  0.5   0.25
#> 3    14      3  0.25  0.75  0

# More robust way to determine triangle ID --------------------------------

# number of breaks in the legend
k = 4
# random data
P <- as.data.frame(prop.table(matrix(runif(3^6), ncol = 3), 1))
# tricolore key without scatterplot
tric_key <- Tricolore(P, 'V1', 'V2', 'V3', breaks = k, show_data = FALSE)$key
# for each observation extract the id of the associated triangle
# in the discrete legend
C <- tricolore:::TernaryMeshCentroids(k)[,-1]
rownames(C) <- 1:nrow(C)
ID <- tricolore:::TernaryNearest(P, C)
P$id <- rownames(ID)
head(P)
#>          V1        V2         V3 id
#> 1 0.2298930 0.3677516 0.40235541 11
#> 2 0.3103613 0.6397081 0.04993057 13
#> 3 0.1882886 0.4128590 0.39885232 11
#> 4 0.3519567 0.3176205 0.33042276 10
#> 5 0.3058110 0.3353727 0.35881629 10
#> 6 0.2034545 0.2939338 0.50261176 12

# plot observations and associated triangles in legend
tric_key +
  geom_text(
    aes(x = V1, y = V2, z = V3, label = id),
    data = P
  )
#> Warning: Ignoring unknown aesthetics: z
```

![](https://i.imgur.com/vfF32GZ.png)

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aboutaaron** [comment]
@jschoeley thanks for this! I'll give it a try shortly! I'm merging these values together because I'd like to move the data outside of R into another environment. I typically do my data cleaning / analysis / joining in R and move to tools I'm more familiar with like Python, node.js or the command line.

**Comment by jschoeley** [comment]
I see. Note to myself: make the export of the data easier in the next release of tricolore.

It still may be easier to export two tables, one for the data along with rgb-encoding and one for the legends triangular mesh. In tricolore these tables are kept separate as well and the legend is drawn as a polygon layer, drawing the triangles, below a point layer, drawing the data distribution.

Happy to see you're results once you feel comfortable sharing.

Best,

Jonas
